"""Repository ports — what the domain expects from persistence.

すべての repo は次の最小契約を持つ（ARCHITECTURE.md §5）:
    get(id)    -> entity        # 見つからなければ NotFoundError
    list(...)  -> list[entity]  # フィルタは kwargs で受ける
    save(e)    -> None          # 新規/更新 を区別しない upsert
    delete(id) -> None          # 冪等

ドメイン特有の問い合わせ（list_drafts, find_similar, get_logs 等）は
各 Protocol に追加する。実装は infrastructure/persistence/ に置く。

注意: 戻り値の entity 型は dataclass だが、移行期間中は dict も受理可能な
よう Any を含める。Step 4 完了後に dict 表現を撤去し、純粋に entity だけに
する予定（ARCHITECTURE.md §0 原則 #3「単一責任 + 不変契約」）。
"""
from __future__ import annotations

from datetime import date
from typing import Any, Protocol

from core.domain.entities import (
    Task, Project, Category, Habit, DiaryEntry, BraindumpSession, WeeklyReview,
)


class TaskRepository(Protocol):
    def get(self, task_id: str) -> Task: ...
    def list(self, **filters: Any) -> list[Task]: ...
    def save(self, task: Task) -> None: ...
    def delete(self, task_id: str) -> None: ...

    def list_drafts(self) -> list[Task]: ...
    def list_by_project(self, project_id: str) -> list[Task]: ...
    def find_similar(self, title: str, limit: int) -> list[Task]: ...
    def archive(self, task_id: str) -> Task: ...
    def restore(self, archived_id: str) -> Task: ...
    def list_archived(self) -> list[Task]: ...
    def list_archived_on(self, date_str: str) -> list[Task]: ...


class ProjectRepository(Protocol):
    def get(self, project_id: str) -> Project: ...
    def list(self, **filters: Any) -> list[Project]: ...
    def save(self, project: Project) -> None: ...
    def delete(self, project_id: str) -> None: ...


class CategoryRepository(Protocol):
    def get(self, category_id: str) -> Category: ...
    def list(self) -> list[Category]: ...
    def save(self, category: Category) -> None: ...
    def delete(self, category_id: str) -> None: ...


class HabitRepository(Protocol):
    def get(self, habit_id: str) -> Habit: ...
    def list(self, **filters: Any) -> list[Habit]: ...
    def save(self, habit: Habit) -> None: ...
    def delete(self, habit_id: str) -> None: ...

    def log_completion(self, habit_id: str, day: date, done: bool) -> None: ...
    def get_logs(self, habit_id: str, start: date, end: date) -> dict[str, bool]: ...
    def calculate_stats(self, habit_id: str, today: date) -> dict[str, Any]: ...


class DiaryRepository(Protocol):
    def get(self, entry_id: str) -> DiaryEntry: ...
    def list(self, start: date, end: date) -> list[DiaryEntry]: ...
    def save(self, entry: DiaryEntry) -> None: ...
    def delete(self, entry_id: str) -> None: ...

    def list_unconsolidated(self, limit: int) -> list[DiaryEntry]: ...
    def mark_consolidated(self, entry_ids: list[str]) -> None: ...


class BraindumpRepository(Protocol):
    def get(self, session_id: str) -> BraindumpSession: ...
    def list(self) -> list[BraindumpSession]: ...
    def save(self, session: BraindumpSession) -> None: ...
    def delete(self, session_id: str) -> None: ...


class WeeklyReviewRepository(Protocol):
    def list(self, limit: int) -> list[WeeklyReview]: ...
    def save(self, review: WeeklyReview) -> None: ...


class StateRepository(Protocol):
    """state.json 相当の key-value 永続化（last_rollover_date 等）。"""
    def load(self) -> dict[str, Any]: ...
    def save(self, state: dict[str, Any]) -> None: ...


class DailyLogRepository(Protocol):
    """日次タスク完了/未完了履歴（カレンダーモーダル・ふりかえり用）。"""
    def add(self, *, date_str: str, task_id: str, title: str,
            status: str, category_id: str | None) -> None: ...
    def list_by_date(self, date_str: str) -> list[dict[str, Any]]: ...
